name: Pre-merge Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  pre-merge_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cucumber Tests
        run: |
          chmod +x ./gradlew
          ./gradlew cucumberCli
