name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cucumber Tests
        run: |
          chmod +x ./gradlew
          ./gradlew cucumberCli
